name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/sales-microservice

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        if: github.event_name == 'push'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build . \
            --file Dockerfile \
            --tag $IMAGE_NAME:$(date +%s) \
            --tag $IMAGE_NAME:latest

      - name: Push Docker images
        if: github.event_name == 'push'
        run: |
          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:$(date +%s)
